`timescale 10ns/1ns

/*****************************************************************************************
* A function to model the neural network behavior
* Consider this function as a blackbox
* DO NOT EDIT THIS FILE
* Inputs: input_1, input_2 - 32 bit floating point numbers
* Output: final_output - 32 bit floating point number
*****************************************************************************************/

function [31:0] nn_model (input [31:0] input_1, input [31:0] input_2);

    // Internal variables
    reg [7:0] ROM [0:511];
    reg [31:0] inter1, inter2;
    reg [63:0] mul1, mul2, mac1, mac2, mul3, mul4, mac3, mac4;
    
    reg ovf_mul1, ovf_mul2, ovf_mul3, ovf_mul4, ovf_mac1, ovf_mac2, ovf_mac3, ovf_mac4, ovf_sb;

    reg [31:0] weight1, weight2, weight3, weight4, bias1, bias2, bias3;
    reg [31:0] shift_bias1, shift_bias2, shift_bias3;
    reg [63:0] result;
    integer addr;

    begin
        addr = 8;
        // -----    Load the rom.data file  -----
        $readmemb("rom_bytes.data", ROM);

        // -----    Pre-processing layer    -----
        shift_bias1 = {ROM[addr], ROM[addr + 1], ROM[addr + 2], ROM[addr + 3]};
	//$display("shift_bias1 = %h\n", shift_bias1);
        addr = addr + 4;
        shift_bias2 = {ROM[addr], ROM[addr + 1], ROM[addr + 2], ROM[addr + 3]};
	//$display("shift_bias2 = %h\n", shift_bias2);
        addr = addr + 4;

        inter1 = $signed(input_1) >>> shift_bias1; 
	//$display("inter1 = %h\n", inter1);
        inter2 = $signed(input_2) >>> shift_bias2;
	//$display("inter2 = %h\n", inter2);
        // -----    Neural Network Input Layer    -----
        // Load weights and biases from ROM
        weight1 = {ROM[addr], ROM[addr + 1], ROM[addr + 2], ROM[addr + 3]};
	//$display("weight1 = %h\n", weight1);
        addr = addr + 4;
        bias1 = {ROM[addr], ROM[addr + 1], ROM[addr + 2], ROM[addr + 3]};
	//$display("bias1 = %h\n", bias1);
        addr = addr + 4;

        weight2 = {ROM[addr], ROM[addr + 1], ROM[addr + 2], ROM[addr + 3]};
	//$display("weight2 = %h\n", weight2);
        addr = addr + 4;
        bias2 = {ROM[addr], ROM[addr + 1], ROM[addr + 2], ROM[addr + 3]};
	//$display("bias2 = %h\n", bias2);
        addr = addr + 4;

        // Neuron calculations
        mul1 = $signed({{32{inter1[31]}}, inter1}) * $signed({{32{weight1[31]}}, weight1});
        ovf_mul1 = (mul1[63:32] != {32{mul1[31]}})? 1'b1 : 1'b0;
         //$display("mul1 = %h\n", mul1);
        mac1 = $signed({{32{mul1[31]}}, mul1[31:0]}) + $signed({{32{bias1[31]}}, bias1});
        ovf_mac1 = (mac1[63:32] != {32{mac1[31]}})? 1'b1 : 1'b0;
	//$display("mac1 = %h\n", mac1);
        mul2 = $signed({{32{inter2[31]}}, inter2}) * $signed({{32{weight2[31]}}, weight2});
        ovf_mul2 = (mul2[63:32] != {32{mul2[31]}})? 1'b1 : 1'b0;

        mac2 = $signed({{32{mul2[31]}}, mul2[31:0]}) + $signed({{32{bias2[31]}}, bias2});
        ovf_mac2 = (mac2[63:32] != {32{mac2[31]}})? 1'b1 : 1'b0;
	//$display("mac2 = %h\n", mac2);
        // -----    Neural Network Output Layer    -----
        // Load weights and bias from ROM
        weight3 = {ROM[addr], ROM[addr + 1], ROM[addr + 2], ROM[addr + 3]};
	//$display("weight3 = %h\n", weight3);
        addr = addr + 4;
        weight4 = {ROM[addr], ROM[addr + 1], ROM[addr + 2], ROM[addr + 3]};
	//$display("weight4 = %h\n", weight4);
        addr = addr + 4;
        bias3 = {ROM[addr], ROM[addr + 1], ROM[addr + 2], ROM[addr + 3]};
	//$display("bias3 = %h\n", bias3);
        addr = addr + 4;

        // Neuron calculation
        mul3 = $signed({{32{mac1[31]}}, mac1[31:0]}) * $signed({{32{weight3[31]}}, weight3});
        ovf_mul3 = (mul3[63:32] != {32{mul3[31]}})? 1'b1 : 1'b0;

        mul4 = $signed({{32{mac2[31]}}, mac2[31:0]}) * $signed({{32{weight4[31]}}, weight4});
        ovf_mul4 = (mul4[63:32] != {32{mul4[31]}})? 1'b1 : 1'b0;

        mac3 = $signed({{32{mul3[31]}}, mul3[31:0]}) + $signed({{32{bias3[31]}}, bias3});
        ovf_mac3 = (mac3[63:32] != {32{mac3[31]}})? 1'b1 : 1'b0;

        mac4 = $signed({{32{mul4[31]}}, mul4[31:0]}) + $signed({{32{mac3[31]}}, mac3[31:0]});
        ovf_mac4 = (mac4[63:32] != {32{mac4[31]}})? 1'b1 : 1'b0;
	//$display("mac4 = %h\n", mac4);
        // -----    Post-processing layer   -----
        shift_bias3 = {ROM[addr], ROM[addr + 1], ROM[addr + 2], ROM[addr + 3]};
	//$display("shift_bias3 = %h\n", shift_bias3);
        addr = addr + 4;
        result = $signed(mac4[31:0]) <<< shift_bias3;
	//$display("result = %h\n", result);
        // -----    Overflow check and final output   -----
        ovf_sb = (result[63:32] != {32{result[31]}})? 1'b1 : 1'b0;

        if (ovf_mul1 | ovf_mul2 | ovf_mul3 | ovf_mul4 | ovf_mac1 | ovf_mac2 | ovf_mac3 | ovf_mac4 | ovf_sb) begin
            // If overflow occurred in any operation, set result the max value
            nn_model = 32'hFFFFFFFF;
        end
        else
        begin
            // Return the final output
            nn_model = result[31:0];
        end
    end
endfunction


module testbench;
  
reg signed [31:0] result;
integer input_1, input_2, cnt, cnt_passed, pass;
reg enable, resetn, clk;
wire total_ovf, total_zero;
wire signed [31:0] final_output;
wire [2:0] ovf_fsm_stage, zero_fsm_stage;

nn nn_test1(final_output, total_ovf, total_zero,ovf_fsm_stage, zero_fsm_stage, enable, resetn, clk, input_1, input_2);


initial begin

	$dumpfile("test.vcd");
    	$dumpvars(0, testbench);

	clk = 1'b0;
	cnt = 0;
	cnt_passed = 0;
	pass = 0;
	resetn = 1'b0;
	enable = 1'b0;
	#2;	
	resetn = 1'b1;
	#2;
end


  
  always begin	
    	
	pass = 0;
	cnt = cnt + 1;	

    	input_1 = $signed($urandom_range(8191, 0) - 4096);
	input_2 = $signed($urandom_range(8191, 0) - 4096);
	//$display("input1 = %h", input_1);
	//$display("input2 = %h", input_2);
	#4;
	enable = 1'b1;
	#1.5;
	enable = 1'b0;
	#12; // important for this first iteration where weights are being loaded - we have a space of 10ns
	result = nn_model(input_1, input_2);

	if (result == final_output) begin
		pass = pass + 1;
	end
	else	begin
		$display("Not passed. Mistake at %0d with input1 = %0h and input2 = %0h. Function result is %0d and nn's final output is %0d", $realtime, input_1, input_2, result, final_output);
	end 

	$display("1. Output of function: %0h and output of nn: %0h", result, final_output); 

    	input_1 = $signed($urandom_range(1073741824, 0) + 1073741823);
	input_2 = $signed($urandom_range(1073741824, 0) + 1073741823);
	//$display("input1 = %h", input_1);
	//$display("input2 = %h", input_2);
	#4;
	enable = 1'b1;
	#1.5;
	enable = 1'b0;
	#12;
	result = nn_model(input_1, input_2);

	if (result == final_output) begin
		pass = pass + 1;
	end
	else	begin
		$display("Not passed. Mistake at %0d with input1 = %0h and input2 = %0h. Function result is %0d and nn's final output is %0d", $realtime, input_1, input_2, result, final_output);
	end 

	$display("2. Output of function: %h and output of nn: %0h", result, final_output); 

	input_1 = $signed($urandom_range(1073741824, 0) - 2147483648);
	input_2 = $signed($urandom_range(1073741824, 0) - 2147483648);
	//$display("input1 = %h", input_1);
	//$display("input2 = %h", input_2);
	#4;
	enable = 1'b1;
	#1.5;
	enable = 1'b0;
	#12;
	result = nn_model(input_1, input_2);

	if (result == final_output) begin
		pass = pass + 1;
	end
	else	begin
		$display("Not passed. Mistake at %0d with input1 = %0h and input2 = %0h. Function result is %0d and nn's final output is %0d", $realtime, input_1, input_2, result, final_output);
	end 

	$display("3. Output of function: %h and output of nn: %0h", result, final_output);

	if (pass == 3) begin
		cnt_passed = cnt_passed + 1;
		$display("Passed: %0d/%0d\n", cnt_passed, cnt);
	end
	else begin
		$display("Passed: %0d/%0d\n", cnt_passed, cnt);
	end

	if (cnt == 100) begin
		$finish;  
	end
			  		
    
  end
    
always begin 
#0.5 clk = ~clk;
end
      
  
endmodule
    
    
